### ISSUE TITLE
Indenting in ranlux

### ISSUE THREAD

**Issue by SimonBiggs** [darcymason/egsnrc#13]
I was just reading a bit on my phone and I saw this:

https://github.com/darcymason/egsnrc/blob/61fd7440ebea33ceec1690c6423ef1354aad4b20/egsnrc/ranlux.py#L213

Is this an issue with indenting here?

If I see things like this did you want me to flag them?

**Comment by darcymason** [comment]
Oops... In general yes, but that code was never used.  I thought I hadn't even committed it - I guess I must have thought to save it "just in case".  The "Python" `randomset` I've been using is just calling the Fortran f2py lib - I wanted the ranlux for exact comparison to Fortan results, but figured we would soon be using Python's much faster `random` or numpy/jax when we didn't care about matching the same random sequence.
