### ISSUE TITLE
An article on JAX usage

### ISSUE THREAD

**Issue by SimonBiggs** [darcymason/egsnrc#16]
An interesting article on using JAX:

https://avinayak.github.io/algorithms/programming/2021/02/19/finding-mona-lisa-in-the-game-of-life.html

Thought this might be of use @ftessier and @darcymason

**Comment by darcymason** [comment]
Thanks - I had a quick read, will go through again in a bit more detail.  TBH my mental model for my efforts was to go to numpy vectorization first and accept that some reworking would be needed for jax.  However, I'll read this again (and maybe some other jax beginner material) and try to incorporate as much as I can into the numpy pass.

I've been slowing down lately on this stuff, but FYI I have a PEGS4 reader in Python mostly done - as a continuation of #15, trying to read in the actual ge0, ge1 arrays (the first ones the code hits).

**Comment by darcymason** [comment]
Hmm, so reading a bit again, might try Google colab, ... but a quick naive question, is it possible to import your own package in the colab notebook? Or do you just have to put all functions in notebook cells?

**Comment by SimonBiggs** [comment]
> is it possible to import your own package in the colab notebook?

It certainly is. Just need to pip install it first, and pip can install from GitHub:

https://colab.research.google.com/drive/1Uh3XFklBQpCSDOY8vSIug32f_rW94_Pa?usp=sharing

Only issue is that Colab currently runs Python 3.7, which clashes with the following at the moment:

https://github.com/darcymason/egsnrc/blob/b457be787b5832fa0c80d1333cb985c9407069cd/setup.py#L45

**Comment by darcymason** [comment]
I can probs deep back to 3.7 fairly easily, it was the transpiler code in 'egsnrc2py' that used some dict stuff that needed 3.9.  I'll see what I can do. Thanks.

**Comment by darcymason** [comment]
Closed as have settled on Numba, at least for now.
