### ISSUE TITLE
Codon compiler?

### ISSUE THREAD

**Issue by darcymason** [darcymason/egsnrc#18]
There's a Python-compatible language compiler out called [Codon](https://github.com/exaloop/codon/blob/develop/README.md) which looks interesting.  It can do static compiling of all or parts of Python code, and is capable of [GPU use](https://docs.exaloop.io/codon/advanced/gpu) and general parallelism.

@ftessier, @SimonBiggs - was wondering if that might be usable for something like this code. I might try it for fun... I have a strange idea of fun, but I suspect many programmers share in that strangeness.  

Simon, I'm curious if you've seen Codon and can comment on the GPU use compared with jax - it looks simpler to me at first glance.

Codon is in very early releases, and linux only at the moment, and also is Business Source License - but from the FAQ: "you can use Codon freely for personal, academic, or other non-commercial applications."

Has anything else happened in the EGS alternative programming language space since we last talked?

**Comment by SimonBiggs** [comment]
Hi Darcy,

I haven't used Codon previously. But it does certainly sound interesting.
And no, I haven't yet advanced this project any further.

I do believe I also share your version of fun 😊

Cheers,
Simon

**Comment by darcymason** [comment]
Closing as have settled on the Numba path, for now at least.
