### ISSUE TITLE
Getting github actions set up

### ISSUE THREAD

**Issue by darcymason** [darcymason/egsnrc#2]
Have github actions mostly working, but pegs4 data not being found.

@ftessier, I'm wondering if you have any ideas?  
In running `configure.expect` , I did not compile any codes, to save time.  Is that relevant?  I thought the pegs4 data stood alone outside this.  And as far as I can tell, HEN_HOUSE is set correctly, unless somehow it is not picked up inside the `f2py`-generated `egsfortran` shared lib.

Here is a link to the failing workflow:
https://github.com/darcymason/egsnrc/runs/1840777335?check_suite_focus=true#step:11:70.
Note that I've `ls`'d the directory and it shows the file there.

I feel this is somewhat import to get a workflow like this going, at least as a sort of template for how to get the Python `egsnrc` set up and running.  I'd like to also add code coverage stats to ensure testing of all branches of code.

I suppose I could copy the `tutor_data` file to my user code directory and see if that works, but will likely run into other problems unless we can understand why this isn't working.

**Comment by ftessier** [comment]
Yes, it is essential to setup a workflow like this. In fact you are reminding me to port my Travis CI actions to github, now that it supports actions! There is no issue with not compiling the individual applications; they can always be compiled by issuing `make` in their respective directories afterwards (in fact this is all the `configure` script does).

I am looking quickly at the failure point, and it strikes be that you don't have `EGS_CONFIG` defined. When configuring EGSnrc, the last message of the configuration indicates a few lines to add to `.bashrc`, notably the `EGS_CONFIG` file and the sourcing of the `egsnrc_bashrc_additions`. I am not sure your action does this, but I would not expect anything to run as expected without `egsnrc_bashrc_additions`. If you are sourcing the additions as part of the install step, let me know and I will dig a little deeper...

**Comment by darcymason** [comment]
> it strikes be that you don't have `EGS_CONFIG` defined

Actually, it is there in the `export` statements, it just doesn't show in the job output or in the environment `tutor4.py` prints out -- but it is a good suggestion and I will look into it again, make sure it is correct and seen in Python.

> and the sourcing of the `egsnrc_bashrc_additions`

I was trying to just set these directly because the environment is created new each run, so .bashrc won't persist.  But I will go back and make sure they were all covered.  Another thought on that is the alias's - I only set the `m` alias because that is called by `make_egsfortan` that runs the `numpy.f2py` conversion.  Perhaps other aliases are important in this scenario?

**Comment by ftessier** [comment]
Ok, I thought so (that `EGS_CONFIG` was defined but not showing. I think it is a sane idea to pluck what's required from the additions script, because ultimately one would like to get rid of this script, it all got over-convoluted (!) for my taste, over time (well, to be honest, before my time 😄 )

**Comment by darcymason** [comment]
Finally got it working.  I think it stemmed from changing the default config name to "actions.conf".  Once matched to my local standard of linux.conf, was able to get it going.

**Comment by SimonBiggs** [comment]
This is so beautiful:

https://github.com/darcymason/egsnrc/runs/1842334740?check_suite_focus=true#step:11:65

:smile: :tada:
