### ISSUE TITLE
Initial electr and next steps

### ISSUE THREAD

**Issue by darcymason** [darcymason/egsnrc#7]
So, good news: the Python `electr` loop is now working for tutor4.  It still calls out through f2py to many functions, e.g. annih, bhaba, brems, moller, etc., and photon histories are tracked entirely in fortran `photon`. However, the basic logic now seems to be correct, at least for the settings of tutor4.  Those nasty `goto`s are gone, and unit tests are in place.

However, I'm seeing it ~50 times slower than pure Fortran. Perhaps that's actually not too bad as a starting point, with no attempt yet to optimize, and the inherent inefficiencies of global variables and f2py interfacing.

I ran a quick profile: about 60% of the time is in the `electr` loops themselves (not including Python functions called from there). The many `ustep` loops per history really add up.  An additional 25% of the time is in 'calc functions' like `compute_eloss_g`, etc. that I added in Python.  Since those are basically math, they can be jitted.  In fact, I did a simple `@numba.jit` decorator on two of them and the speed-up was factor ~8-10.

I'm interested in thoughts on next steps. @simonbiggs, any thoughts from the GPU perspective? Or on trying PyPy or other 'compiling'?

I'm still contemplating, but based on the initial profiling noted above, I'm thinking the way forward may be to move loops out of Python and into arrays as much as possible -i.e. replace current one-history-at-a-time with numpy arrays of many particles tracked at once.  That also gets us closer to GPU-compatible code. But that requires some significant refactoring to get there.  Seems to me, though, that it is mostly the kind required to convert to any language - clear inputs and outputs, and minimal globals (except perhaps interaction data).

**Comment by SimonBiggs** [comment]
I'm just on leave at the moment (only just got back into intermittent phone reception 🙂) but this looks perfect for me to make a priority to dig in and gets my hands dirty with when I get back. I'll be back early March ☺️.

**Comment by darcymason** [comment]
Sounds good, @SimonBiggs ... meanwhile I'm been plugging away at various subroutines, etc - annih, bhabha, brems... not hard to convert because mostly just math.  After that, probably another round of tests to make sure they are all working correctly under various user settings, etc.  I've started to realize that everything is so interconnected (heavily reliant on globals) that we probably can't do much on vectorizing or any other major code reorg without having almost everything converted over.  I'm back to the simple target of a 'first pass' conversion where everything works on Python, but in pretty much identical fashion to the original, ... then we can be in a good position for restructuring.

**Comment by SimonBiggs** [comment]
> meanwhile I'm been plugging away at various subroutines

If you find yourself looking for what to prioritise next, the section of egs that does some of the following stages might be worth a look in:

https://github.com/SimonBiggs/pyegsnrc/issues/1

But only if there isn't something else that is a natural next step.

> we probably can't do much on vectorizing or any other major code reorg without having almost everything converted over

Kk

**Comment by darcymason** [comment]
> If you find yourself looking for what to prioritise next, the section of egs that does some of the following stages might be worth a look in:

Sure, I'll have a look and see what I can pick up - Maybe I can look at the main `photon` loop and try to summarize the random sampling towards the different interactions.

**Comment by darcymason** [comment]
Closing as this is old information -- no longer using call-outs to Fortran code with the current code and GPU use.
