### ISSUE TITLE
Single vs double precision

### ISSUE THREAD

**Issue by darcymason** [darcymason/egsnrc#8]
I made a comment somewhere earlier about seeing minor differences in the last few digits of Python results vs Fortran results, and that I would leave it for a while.  Well, ... it kept niggling at me so I investigated, and it is solved in the next PR - I'm just trying to fix up some of the tests.

It turns out that Fortran float literals are assumed to be single precision, even when assigned to a double precision variable, unless marked as double with e.g. "D0" on the end.  Python is all double-precision.  So, e.g. in `compute-eloss`, the formula has a constant `0.333333`, which gives a  double-precision number more like 0.333332985... vs in Python, 0.33333299999999.... (Aside: is the 0.333333 really 1/3?).  There are other constants in these formulas too, but they all happen to be representable in exact binary IEEE 754: e.g. 0.25, 0.5, 2.0, 4.0.  

A similar thing happened with some of the global common constants - `rm`, `prm`, `prm2`.  They are initialized with single-prec values.  I copied the values as seen in Fortran, to make Python match.  

But, I wonder if constants such as these should be updated in original EGSnrc?  It seems now that the default is to use all double precision.  These are small differences, to be sure, but nevertheless they can add up over many histories.  It feels strange to put "wrong" values in Python but it is very useful to be able to prove exact results vs the original Fortran.  I suppose these could be put in variables, and made "wrong" just for unit tests.

**Comment by SimonBiggs** [comment]
> It feels strange to put "wrong" values in Python but it is very useful to be able to prove exact results vs the original Fortran. I suppose these could be put in variables, and made "wrong" just for unit tests.

Yeah, I agree it is weird to propagate "wrong" constants. The value in being able to validate against original what code is high for unit tests. So I think this last approach here is ideal 🙂
